#:schema node_modules/wrangler/config-schema.json
name = "arishi-website"
compatibility_date = "2024-10-02"
main = "./build/worker/index.js"
assets = { directory = "./build/client" }

[observability]
enabled = true

[[services]]
binding = "PUBLIC_DATA_SERVICE"
service = "arishi-website-api"
entrypoint = "PublicDataService"

[[services]]
binding = "WEBSITE_API"
service = "arishi-website-api"
