#:schema node_modules/wrangler/config-schema.json
name = "react-router-cloudflare"
compatibility_date = "2024-12-25"

workers_dev = true
main = "./workers/server.ts"

[assets]
directory = "./build/client"

[observability]
enabled = true

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare"

[[services]]
binding = "PUBLIC_DATA_SERVICE"
service = "arishi-website-api"
entrypoint = "PublicDataService"

[[services]]
binding = "WEBSITE_API"
service = "arishi-website-api"
