#:schema node_modules/wrangler/config-schema.json
name = "arishi-openauth-api"
main = "src/index.ts"
compatibility_date = "2025-02-24"

# This API can only be accessed via bindings
workers_dev = false

[observability]
enabled = true

[placement]
mode = "smart"
