#:schema node_modules/wrangler/config-schema.json
name = "domain-redirect"
main = "src/index.ts"
compatibility_date = "2025-02-24"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[placement]
mode = "smart"
