import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
import * as build from '../build/server';

// @ts-expect-error - Some conflict with build output
export const onRequest = createPagesFunctionHandler({ build });
