#:schema node_modules/wrangler/config-schema.json
name = "arishi-website-api"
main = "src/index.ts"
compatibility_date = "2024-10-02"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[placement]
mode = "smart"
