// Generated by Wrangler on Thu Apr 11 2024 16:44:59 GMT+1000 (Australian Eastern Standard Time)
// by running `wrangler types`

// eslint-disable-next-line @typescript-eslint/no-empty-interface
interface Env {}
