name: Deploy Cloudflare Pages

on:
  workflow_run:
    workflows: ['CI']
    types: [completed]
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Build and deploy CF Pages
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm build

      - name: Deploy arishi-website-webapp
        id: deploy-arishi-website-webapp
        uses: cloudflare/wrangler-action@v3.6.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy ./build/client --project-name=adishwar-rishi-website
          workingDirectory: 'apps/arishi-website-webapp'
          packageManager: 'pnpm'

      - name: Comment with deploy link
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const apps = [
              { name: 'arishi-website-webapp', url: process.env.ARISHI_WEBSITE_WEBAPP_DEPLOYMENT_URL },
              // Add more apps here
            ];
            const commitHash = context.payload.pull_request.head.sha;
            const status = '✅  Deploy successful!';

            let tableHeader = '| App Name | Last Commit | Preview URL | Status |';
            let tableDivider = '| --------- | ----------- | ----------- | ------ |';
            let tableRows = apps.map(app => `| ${app.name} | \`${commitHash.substring(0, 7)}\` | ${app.url} | ${status} |`).join('\n');

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
              # 🌩 Deploying with Cloudflare Pages
              ${tableHeader}
              ${tableDivider}
              ${tableRows}
              `
            });
        env:
          ARISHI_WEBSITE_WEBAPP_DEPLOYMENT_URL: ${{ steps.deploy-arishi-website-webapp.outputs.deployment-url }}
